---
title: "Overview"
output: html_document
date: '2023-03-16'
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=6, fig.asp = 0.618, collapse=TRUE) 
```

```{r, echo=F, message=F, warning=F}
library(tidyverse)
library(dplyr)
library(GGally)    
library(ggiraph)
library(ggiraphExtra) 
library(lme4)

angle_data=read.csv('Data/Updated.csv',
                    col.names=c("depression_angle","julian_day","offset","ID","year", "AoD_J","bradford", "month"))%>%
  filter(!(ID=="NA"))

angle_data$depression_angle=as.integer(angle_data$depression_angle)
angle_data$ID=as.factor(angle_data$ID)
angle_data$year=as.factor(angle_data$year)
angle_data$month=as.factor(angle_data$month)

low_offset_data=angle_data%>%
  filter(offset<3)

low_ID_data=low_offset_data%>%
  filter(!ID=="185",!ID=="356", !ID=="44", !ID=="56", !ID=="531")


grey_annual_change=low_offset_data%>%
  group_by(ID, year) %>%
  filter(!(ID=="185"))%>%
  summarize(first_sight=min(julian_day),
            last_sight=max(julian_day)) %>%   # groups by ID, then year and adds 2 new columns
  ungroup()%>%
  left_join(.,low_offset_data%>%select(ID, julian_day, depression_angle), 
            by=c("ID"="ID", "first_sight"="julian_day"))%>%
  rename(first_sight_depression_angle=depression_angle)%>%
  left_join(.,low_offset_data%>%select(ID, julian_day, depression_angle), 
            by=c("ID"="ID", "last_sight"="julian_day"))%>%
  rename(last_sight_depression_angle=depression_angle)%>%
  # Deal with multiple pictures (and thus depression angles) collected on same day by taking the mean
  group_by(ID, year, first_sight, last_sight)%>%
  summarize(first_sight_depression_angle=mean(first_sight_depression_angle), 
            last_sight_depression_angle=mean(last_sight_depression_angle))%>%
  ungroup()%>%
  # Calculate sighting period and change in depression angle for each ID and each year
  group_by(ID, year) %>%
  mutate(sight_period_days=last_sight-first_sight,
         diff_depression_angle=last_sight_depression_angle-first_sight_depression_angle)


filtered_grey_annual_change=low_offset_data%>%
  group_by(ID, year) %>%
  summarize(first_sight=min(julian_day),
            last_sight=max(julian_day)) %>%   # groups by ID, then year and adds 2 new columns
  ungroup()%>%
  left_join(.,low_offset_data%>%select(ID, julian_day, depression_angle), 
            by=c("ID"="ID", "first_sight"="julian_day"))%>%
  rename(first_sight_depression_angle=depression_angle)%>%
  left_join(.,low_offset_data%>%select(ID, julian_day, depression_angle), 
            by=c("ID"="ID", "last_sight"="julian_day"))%>%
  rename(last_sight_depression_angle=depression_angle)%>%
  # Deal with multiple pictures (and thus depression angles) collected on same day by taking the mean
  group_by(ID, year, first_sight, last_sight)%>%
  summarize(first_sight_depression_angle=mean(first_sight_depression_angle), 
            last_sight_depression_angle=mean(last_sight_depression_angle))%>%
  ungroup()%>%
  # Calculate sighting period and change in depression angle for each ID and each year
  group_by(ID, year) %>%
  mutate(sight_period_days=last_sight-first_sight,
         diff_depression_angle=last_sight_depression_angle-first_sight_depression_angle)
  

# removing outliers
filtered_grey_annual_change=filtered_grey_annual_change%>%
  filter(diff_depression_angle>-1.75,
         diff_depression_angle<2)


year_w_ID_count=grey_annual_change %>%
  group_by(year)%>%
  summarise(number_of_IDs=n_distinct(ID))

high_year_w_ID_count=year_w_ID_count%>%
  filter(number_of_IDs>=7)



compare_angle_data=read.csv('Data/Updated.csv',
                            col.names=c("AoD_K","ratioA", "ratio","julian_day","offset","ID","year", "bradford","AoD_J", "month"))%>%
  filter(!(ID=="NA"))

compare_angle_data$ID=as.factor(compare_angle_data$ID)
compare_angle_data$year=as.factor(compare_angle_data$year)
compare_angle_data$month=as.factor(compare_angle_data$month)
compare_angle_data$bradford=as.factor(compare_angle_data$bradford)
```

***

#### General count

```{r}
ggplot(angle_data)+
  geom_bar(aes(x=year, fill=ID))+
  xlab("Year")+
  ylab("Measurements")+
  theme_bw()

ggplot(angle_data)+
  geom_bar(aes(x=ID))+
  xlab("ID")+
  ylab("Measurements")+
  theme_bw()

ggplot(angle_data)+
  geom_bar(aes(x=month))+
  xlab("Month")+
  ylab("Count")+
  theme_bw()
```

***

#### General overview with all data

```{r, echo=F, message=F, warning=F}
ggplot(angle_data, aes(x=julian_day, y=depression_angle))+
  geom_point()+
  geom_smooth(method=lm, SE=F)+
  theme_bw()+
  xlab("Julian Day")+
  ylab("Depression Angle")

ggplot(angle_data)+
  geom_point(aes(x=julian_day, y=depression_angle))+
  geom_smooth(aes(x=julian_day, y=depression_angle, method="lm"))+
  xlab("Julian Day")+
  ylab("Body Condition Angle")+
  theme_bw()

ggplot(data=angle_data)+
  geom_boxplot(aes(y=ID, x=depression_angle))+
  theme_bw()+
  xlab("Body Condition Angle")
```

##### By year/ID

```{r, echo=F, message=F, warning=F}
ggplot(angle_data, aes(x=julian_day, y=depression_angle, colour=year))+ 
  geom_point()+
  theme_bw()+
  xlab("Julian Day")+
  ylab("Depression Angle")

ggplot(angle_data, aes(x=julian_day, y=depression_angle, colour=year))+
  geom_point()+
  facet_wrap(~ID, nrow=3)+
  theme_bw()+
  xlab("Julian Day")+
  ylab("Body Condition Angle")

ggplot(angle_data, aes(x=julian_day, y=depression_angle, colour=ID))+ 
  geom_point()+
  theme_bw()+
  xlab("Julian Day")+
  ylab("Depression Angle")

year_data=angle_data%>%
  filter(!year%in%c(1990,1991,1992,1998,2000,2002,2003,2004,2005,2007,2008))

ggplot(year_data, aes(x=julian_day, y=depression_angle, colour=ID))+
  geom_point()+
  facet_wrap(~year, nrow=4)+
  theme_bw()+
  xlab("Julian Day")+
  ylab("Body Condition Angle")
```

***

#### General overview with low offset data

```{r, echo=F, message=F, warning=F}
ggplot(low_offset_data, aes(x=julian_day, y=depression_angle))+
  geom_point()+
  geom_smooth(method=lm, SE=F)+
  theme_bw()+
  xlab("Julian Day")+
  ylab("Depression Angle")

ggplot(low_offset_data)+
  geom_point(aes(x=julian_day, y=depression_angle))+
  geom_smooth(aes(x=julian_day, y=depression_angle, method="lm"))+
  xlab("Julian Day")+
  ylab("Body Condition Angle")+
  theme_bw()

ggplot(data=low_offset_data)+
  geom_boxplot(aes(y=ID, x=depression_angle))+
  theme_bw()+
  xlab("Body Condition Angle")
```

##### By year/ID

```{r, echo=F, message=F, warning=F}
ggplot(low_offset_data, aes(x=julian_day, y=depression_angle, colour=year))+ 
  geom_point()+
  theme_bw()+
  xlab("Julian Day")+
  ylab("Depression Angle")

ggplot(low_offset_data, aes(x=julian_day, y=depression_angle, colour=ID))+
  geom_point()+
  facet_wrap(~year, nrow=5)+
  theme_bw()+
  xlab("Julian Day")+
  ylab("Body Condition Angle")

ggplot(low_offset_data, aes(x=julian_day, y=depression_angle, colour=ID))+ 
  geom_point()+
  theme_bw()+
  xlab("Julian Day")+
  ylab("Depression Angle")

ggplot(low_offset_data, aes(x=julian_day, y=depression_angle, colour=year))+
  geom_point()+
  facet_wrap(~ID, nrow=3)+
  theme_bw()+
  xlab("Julian Day")+
  ylab("Body Condition Angle")
```

***

#### Time in Sound and change in angle

```{r, echo=F, message=F, warning=F}
ggplot(data=grey_annual_change)+
  geom_point(aes(x=sight_period_days, y=diff_depression_angle, color=year)) +
  geom_smooth(aes(x=sight_period_days, y=diff_depression_angle), method="lm") +
  facet_wrap(~ID)+
  theme_bw() +
  scale_color_discrete(name="whale ID") +
  ylab("Difference in depression angle between\nfirst and last sighting of the season") + xlab("Sighting period (days)")

ggplot(data=grey_annual_change)+
  geom_point(aes(x=sight_period_days, y=diff_depression_angle, color=ID)) +
  geom_smooth(aes(x=sight_period_days, y=diff_depression_angle), method="lm") +
  facet_wrap(~year)+
  theme_bw() +
  scale_color_discrete(name="whale ID") +
  ylab("Difference in depression angle between\nfirst and last sighting of the season") + xlab("Sighting period (days)")

ggplot(filtered_grey_annual_change)+
  geom_point(aes(x=sight_period_days, y=diff_depression_angle, colour=ID))+
  stat_smooth(method = "lm", se=F, aes(x=sight_period_days, y=diff_depression_angle, colour=ID))+
  xlab("Sighting Period (Days)")+
  ylab("Difference in first and last BC angle of the season")
  theme_bw()
```

##### Competition?

```{r, echo=F, message=F, warning=F}
ggplot(data=year_w_ID_count)+
  geom_point(aes(x=year,
                 y=number_of_IDs))

summary(year_w_ID_count$number_of_IDs)
# 3rd quartile is 7 individuals and above

high_comp_years=filtered_grey_annual_change%>%
  left_join(high_year_w_ID_count, by="year")%>%
  select(year,diff_depression_angle,number_of_IDs,ID)%>%
  filter(!is.na(number_of_IDs))
  
ggplot(data=high_comp_years)+
  geom_point(aes(x=number_of_IDs,
             y=diff_depression_angle,     
             colour=year))
```

***

#### Linear regression

```{r, echo=F, message=F, warning=F}
# All data
lm_angle_vs_day = lm(depression_angle~julian_day, data=angle_data)
summary(lm_angle_vs_day)

# Low offset
lm_angle_vs_day_low_offset = lm(depression_angle~julian_day, data=low_offset_data)
summary(lm_angle_vs_day_low_offset)

# Low offset + low ID
lm_angle_vs_day_low_ID = lm(depression_angle~julian_day, data=low_ID_data)
summary(lm_angle_vs_day_low_ID)


# Jasmine
# All data
lm_angle_vs_day = lm(AoD_J~julian_day, data=angle_data)
summary(lm_angle_vs_day)

# Low offset
lm_angle_vs_day_low_offset = lm(AoD_J~julian_day, data=low_offset_data)
summary(lm_angle_vs_day_low_offset)

# Low offset + low ID
lm_angle_vs_day_low_ID = lm(AoD_J~julian_day, data=low_ID_data)
summary(lm_angle_vs_day_low_ID)


# Significance by ID/year
linear_ID=lm(depression_angle~julian_day:ID, data=angle_data)
summary(linear_ID)

linear_year=lm(depression_angle~julian_day:year, data=angle_data)
summary(linear_year)
```

***

#### Mixed effects

```{r, echo=F, message=F, warning=F}
# Only year as random
mixed=lmer(depression_angle~julian_day + (1|year), data=angle_data)
summary(mixed)

# Year, ID, and offset as random
mixed_ext=lmer(depression_angle~julian_day  + (1|year) + (1|ID) + (1|offset), data=angle_data)
summary(mixed_ext)

# 3 random from low offset data
mixed_low_offset=lmer(depression_angle~julian_day + (1|year)+ (1|ID) + (1|offset), data=low_offset_data)
summary(mixed_low_offset)

# 3 random from low ID data
mixed_low_ID=lmer(depression_angle~julian_day + (1|year)+ (1|ID) + (1|offset), data=low_ID_data)
summary(mixed_low_ID)


# Jasmine  
# Year, ID, and offset as random
mixed_ext=lmer(AoD_J~julian_day  + (1|year) + (1|ID) + (1|offset), data=angle_data)
summary(mixed_ext)

# 3 random from low offset data
mixed_low_offset=lmer(AoD_J~julian_day + (1|year)+ (1|ID) + (1|offset), data=low_offset_data)
summary(mixed_low_offset)

# 3 random from low ID data
mixed_low_ID=lmer(AoD_J~julian_day + (1|year)+ (1|ID) + (1|offset), data=low_ID_data)
summary(mixed_low_ID)
```

***

#### Inter-researcher

```{r, echo=F, message=F, warning=F}
# t test
t.test(x=compare_angle_data$AoD_J, y=compare_angle_data$AoD_K, paired=T)

# Correlation
cor(x=compare_angle_data$AoD_J, y=compare_angle_data$AoD_K, use="complete.obs")

plot(x=compare_angle_data$AoD_J, y=compare_angle_data$AoD_K)
```

#### Bradford

```{r, echo=F, message=F, warning=F}
ggplot(data = compare_angle_data)+
  geom_point(aes(x=AoD_J, y=bradford))+
  xlab("Jasmine's Measurements")+
  ylab("Bradford Score")
  facet_wrap("ID")
```

















